### ISSUE TITLE
Implement remember me feature

### ISSUE THREAD

**Issue by davidabrahams** [davidabrahams/Spring-Initiative#13]

**Comment by shrutiyer** [comment]
Just a note for whoever resolves this issue: I am not entirely sure how we will end up implementing it. If we are using session ids and saving it to cookies, it is not safe.
If we are not getting an SSL certificate, saving cookies locally and sending/receiving info with session id isn't smart. Over an unencrypted network, packet sniffers can easily steal cookies and thereby steal sessions.

**Comment by shrutiyer** [comment]
Group decided not to implement it
