### ISSUE TITLE
form breaks when hitting enter instead of clicking submit button

### ISSUE THREAD

**Issue by BrennaManning** [davidabrahams/Spring-Initiative#158]

**Comment by davidabrahams** [comment]
which form?

**Comment by BrennaManning** [comment]
I checked daily and long term but I'm guessing all of them
If you hit the enter key instead of clicking submit you'll see

**Comment by davidabrahams** [comment]
Interesting. My guess is that hitting enter causes the state to change? I'm
not sure. Whoever gets to this issue, I'd recommend checking states to
start.
