### ISSUE TITLE
Test code in other browsers and versions

### ISSUE THREAD

**Issue by nmohamed** [davidabrahams/Spring-Initiative#18]
With/without HTML5, Firefox/Chrome/IE, etc.

**Comment by shrutiyer** [comment]
Things I have noted in Firefox:
1. Dropdown looks weird in both forms and Viz tab
2. Edit Student form has "Overview" which is required (not sure). The website asks me to fill it but it submits the form anyway.
3. Resizing works pretty well
4. Bar charts for consecutive dates overlap (see Rose Watson Stars). Not an error but maybe we want it to not overlap?
5. Colors look pretty good to my eyes but others might have a different opinion.

**Comment by shrutiyer** [comment]
All the functionalities remain intact in Firefox. Only things that needed to make the webapp in Firefox nicer are css/bootstrap, etc.
