### ISSUE TITLE
Remove Incorrect Password Error

### ISSUE THREAD

**Issue by shrutiyer** [davidabrahams/Spring-Initiative#20]
- Remove error after starting to retype password
- Be less specific about wrong password or wrong email

**Comment by nmohamed** [comment]
what's the error?

**Comment by davidabrahams** [comment]
@shrutiyer I haven't had any issues?

**Comment by shrutiyer** [comment]
Don't tell the users that it was incorrect password. Instead say incorrect username/password pair.
