### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by nmohamed** [davidabrahams/Spring-Initiative#3]
~~create models~~
test database
add routes
add login
add sessions
make it look decent
make it look pretty

**Comment by davidabrahams** [comment]
This is fine for now since we had to define initial things we had to do, but for the rest of the project we should probably open up issues and then close them as they complete. Thoughts?

**Comment by nmohamed** [comment]
Yup, I just put this here as general things we need to do but we should make things more specific
