### ISSUE TITLE
Students and allStudents are both being used to reference sidebar things on angular controllers

### ISSUE THREAD

**Issue by aconsilvio** [davidabrahams/Spring-Initiative#58]
We need to pick one.  It looks like although initially everything was set up with allStudents, all the HTML files references students.

**Comment by davidabrahams** [comment]
Good catch. I just fixed this in my PR (I think). Might have missed something.

**Comment by davidabrahams** [comment]
@aconsilvio OHHH this is why you needed a page refresh to view a new student!

**Comment by aconsilvio** [comment]
Yeah I just fixed that which is how I noticed it, so I think from my quick lookover everything should be ok now- I figured everyone should know. :)

**Comment by davidabrahams** [comment]
Okay cool. Is it fixed on the `fancy-sidebar` branch?

**Comment by davidabrahams** [comment]
Nope its not just tested. Gimme a sec ill fix it
